### ISSUE TITLE
problem compiling contract

### ISSUE THREAD

**Issue by cryptid11** [OffchainLabs/arbc-solidity#3]
on `truffle migrate --reset --network arbitrum` I get:

```
Traceback (most recent call last):
  File "/usr/local/bin/arbc-truffle-compile", line 4, in <module>
    __import__('pkg_resources').run_script('arbc-solidity==0.1.0', 'arbc-truffle-compile')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1493, in run_script
    code = compile(source, script_filename, 'exec')
  File "/usr/local/lib/python3.5/dist-packages/arbc_solidity-0.1.0-py3.5.egg/EGG-INFO/scripts/arbc-truffle-compile", line 34
    f.write(f"{instr} {instr.path}")
                                  ^
SyntaxError: invalid syntax

```

full trackeback: http://paste.debian.net/1086338/

**Comment by tpobryan** [comment]
What version of python are you using? The f-string formatting used here was introduced in python 3.6. If you are using an earlier version, that would explain the error.

**Comment by ewfelten** [comment]
Added a requirement to the dev quickstart guide, saying that python3 must be at least version 3.6.  Will remove/modify that requirement once this issue is resolved.

**Comment by cryptid11** [comment]
yes that was indeed the problem, thanks

**Comment by hkalodner** [comment]
Glad to hear it's working now!

Minimum requirement is now dropped down to 3.5.3. We currently have a dependency on web3 which requires that so dropping it lower would require dropping that dependency. Closing this issue since it's working for you now.
